openapi: 3.0.0
info:
  title: HKID Appointment API
  version: 1.0.0
  description: API for managing HKID appointment bookings

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /api/appointments:
    get:
      summary: Get all appointments
      responses:
        '200':
          description: A list of appointments
    post:
      summary: Create a new appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '201':
          description: Appointment created

components:
  schemas:
    Appointment:
      type: object
      properties:
        id:
          type: integer
        name_en:
          type: string
        name_zh:
          type: string
        gender:
          type: string
        dob:
          type: string
          format: date
        address:
          type: string
        hkid:
          type: string
        phone:
          type: string
        email:
          type: string
        date:
          type: string
        time:
          type: string
        location:
          type: string
